// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"book-store/database"
	"book-store/handler"
	"book-store/repository"
	"book-store/router"
	"book-store/service"
	"net/http"
)

// Injectors from wire.go:

func InitializeRouterHandler() http.Handler {
	db := database.NewPostgresDB()
	userRepository := repository.NewUserRepo(db)
	userService := service.NewUserService(userRepository)
	authHandler := handler.NewAuthHandler(userService)
	paymentMethodRepository := repository.NewPaymentMethodRepository(db)
	paymentMethodService := service.NewPaymentMethodService(paymentMethodRepository)
	paymentMethodHandler := handler.NewPaymentMethodHandler(paymentMethodService)
	httpHandler := router.NewRouter(authHandler, paymentMethodHandler)
	return httpHandler
}
